services:

  proxy:
    depends_on: 
      - frontend
    image: patricksyoung/mosaic-proxy:2.5
    ports:
      - '80:80'
    networks:
      - mosaic-network

  frontend:
    build:
      context: ./mosaic-frontend
      dockerfile: Dockerfile
    networks:
      - mosaic-network

  backend:
    image: patricksyoung/mosaic-backend:3.0
    volumes:
      - mosaic-volume:/var/lib/video
      - ./assets/330055:/var/lib/video/330055
    networks:
      - mosaic-network

volumes:
  mosaic-volume:

networks:
  mosaic-network:
    driver: bridge # a user defined bridge is required; the default bridge network doesn't support name resolution

